[package]
org = "csv"
name = "data_cleaner"
version = "0.1.0"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"

[build-options]
observabilityIncluded = true
